runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
  login: admin

libraries:
- name: ssl
  version: latest

env_variables:
  PROJECT: 'transat-data'  # Enter your own project ID here
  BUCKET: 'transat-data'  # Name of the bucket where the Dataflow template resides
  TEMPLATE_NAME: 'bq2bq' # Enter the name of your Dataflow template